### ISSUE TITLE
About ISIC2018 models weights

### ISSUE THREAD

**Issue by dongqing065269** [sara-kassani/ISIC2018#1]
Hello,can i ask a question that if is convenient,can you share the pretrained  models weights? Thanks very much!

**Comment by sara-kassani** [comment]
Hello, below link is shared folder for models and weights. Unfortunately, I don't have the Xception weights.

https://drive.google.com/open?id=1dh6Lfa1wUNu_EQKNy_C2PfWDxMg8IjoH

**Comment by dongqing065269** [comment]
Thanks very very much!
